# Generated by Django 2.2.2 on 2019-08-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tel_tools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('template', models.TextField(verbose_name='template')),
            ],
            options={
                'db_table': 'notifier_messages',
            },
        ),
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tel_tools.TelegramBot')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tel_tools.TelegramChannel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_routes', to='notifier.NotificationMessage')),
            ],
            options={
                'db_table': 'notifier_routes',
            },
        ),
    ]
