# Generated by Django 2.2.3 on 2019-08-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.TextField()),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=60)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifier.TelegramBot')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifier.TelegramChannel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifier.NotificationMessage')),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
