# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('used_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dns_bank_ip',
            },
        ),
        migrations.CreateModel(
            name='SystemDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dns_domains',
            },
        ),
        migrations.AddField(
            model_name='bankip',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_updater.SystemDomain'),
        ),
    ]
