# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-10 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankip',
            old_name='created_date',
            new_name='created_time',
        ),
    ]
