# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-10 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0002_auto_20190610_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdomain',
            name='dns_record',
            field=models.CharField(default='dns', max_length=32),
            preserve_default=False,
        ),
    ]
