# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0003_systemdomain_dns_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdomain',
            name='dns_record',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
