# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0005_auto_20190610_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdomain',
            name='dns_record',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
