# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0006_auto_20190610_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdomain',
            name='zone_id',
            field=models.CharField(default='zone_id', max_length=32),
            preserve_default=False,
        ),
    ]
