# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 11:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0007_systemdomain_zone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(db_index=True, max_length=15)),
                ('api_response', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'dns_domain_logger',
            },
        ),
        migrations.CreateModel(
            name='DomainNameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sub_domain_name', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('dns_record', models.CharField(blank=True, editable=False, max_length=32, null=True)),
                ('disable', models.BooleanField()),
            ],
            options={
                'db_table': 'dns_domain_records',
            },
        ),
        migrations.CreateModel(
            name='DomainZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('zone_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dns_domain_zone',
            },
        ),
        migrations.RemoveField(
            model_name='bankip',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='bankip',
            name='used_date',
        ),
        migrations.AddField(
            model_name='bankip',
            name='server',
            field=models.CharField(choices=[('', ''), ('', '')], db_index=True, default='exmple.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankip',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bankip',
            name='used_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bankip',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='SystemDomain',
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_updater.DomainZone'),
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_updater.DomainLogger'),
        ),
        migrations.AddField(
            model_name='domainlogger',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_updater.DomainNameRecord'),
        ),
    ]
