# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0008_auto_20190612_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainnamerecord',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ip_updater.DomainLogger'),
        ),
    ]
