# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 14:28
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0013_auto_20190612_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlogger',
            name='api_response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
