# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0015_auto_20190613_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankip',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
