# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0017_auto_20190617_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainnamerecord',
            name='log',
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='dns_record',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='sub_domain_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
