# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_updater', '0018_auto_20190617_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankip',
            name='server',
            field=models.CharField(choices=[('CloudFlare', 'CloudFlare')], db_index=True, max_length=50),
        ),
    ]
