# Generated by Django 2.2.2 on 2019-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ping_checker_domain_list',
            },
        ),
    ]
