# Generated by Django 2.2.2 on 2019-06-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainpinglog',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_check.DomainName'),
        ),
    ]
