# Generated by Django 2.2.2 on 2019-08-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tel_tools', '0002_auto_20190828_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(db_index=True, max_length=50)),
                ('port', models.IntegerField(db_index=True)),
                ('secret_key', models.CharField(max_length=32)),
                ('proxy_tag', models.CharField(blank=True, max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tel_tools.TelegramUser')),
            ],
            options={
                'db_table': 'mtproxy_proxy',
                'unique_together': {('host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='MTProxyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('stat_message', models.TextField()),
                ('number_of_users', models.PositiveIntegerField(null=True)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promoter.MTProxy')),
            ],
            options={
                'db_table': 'mtproxy_stats',
            },
        ),
        migrations.CreateModel(
            name='ChannelPromotePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('from_time', models.DateTimeField()),
                ('until_time', models.DateTimeField()),
                ('channel', models.CharField(max_length=60)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promoter.MTProxy')),
            ],
            options={
                'db_table': 'mtproxy_promote_plan',
            },
        ),
    ]
