# Generated by Django 2.2.2 on 2019-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtproxystat',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='channelpromoteplan',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AddField(
            model_name='mtproxy',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mtproxy',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='stat_message',
            field=models.TextField(blank=True),
        ),
    ]
