# Generated by Django 2.2.2 on 2019-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtproxy',
            name='proxy_tag',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
