# Generated by Django 2.2.2 on 2019-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxybot', '0002_auto_20190629_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtproxy',
            name='proxy_tag',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
