# Generated by Django 2.2.2 on 2019-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0002_auto_20190904_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtproxy',
            options={'verbose_name': 'MTProto proxy', 'verbose_name_plural': 'MTProto proxies'},
        ),
        migrations.AlterModelOptions(
            name='mtproxystat',
            options={'ordering': ('-id',), 'verbose_name': 'proxy stat'},
        ),
        migrations.AlterField(
            model_name='mtproxy',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='mtproxy',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='is_enable'),
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='number_of_users',
            field=models.PositiveIntegerField(null=True, verbose_name='user connected'),
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='stat_message',
            field=models.TextField(blank=True, verbose_name='stat_message'),
        ),
        migrations.DeleteModel(
            name='ChannelPromotePlan',
        ),
    ]
