# Generated by Django 2.2.2 on 2019-06-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxybot', '0003_auto_20190629_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtproxy',
            name='proxy_tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
