# Generated by Django 2.2.2 on 2019-10-06 13:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0004_auto_20191006_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelUserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('channel', models.CharField(editable=False, max_length=150, verbose_name='promoted_channel')),
                ('statistics', jsonfield.fields.JSONField(default=dict, editable=False, verbose_name='statistics')),
                ('proxy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='promoter.MTProxy')),
            ],
            options={
                'db_table': 'mtproxy_channel_stats',
                'index_together': {('proxy', 'channel')},
            },
        ),
    ]
