# Generated by Django 2.2.2 on 2019-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0005_channeluserstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeluserstat',
            options={'ordering': ('-id',), 'verbose_name': 'stat of channel', 'verbose_name_plural': 'stat of channels'},
        ),
        migrations.AlterModelOptions(
            name='mtproxystat',
            options={'ordering': ('-id',), 'verbose_name': 'stat of proxy', 'verbose_name_plural': 'stat of proxies'},
        ),
        migrations.AlterField(
            model_name='mtproxystat',
            name='promoted_channel',
            field=models.CharField(max_length=50, verbose_name='promoted channel'),
        ),
    ]
