# Generated by Django 2.2.2 on 2019-10-10 07:33

from django.db import migrations, models
from django.db.models.functions import Concat


def update_slugs(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MTProxy = apps.get_model("promoter", "MTProxy")
    db_alias = schema_editor.connection.alias
    MTProxy.objects.using(db_alias).update(slug=Concat('host', models.Value(':'), 'port'))


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0006_auto_20191006_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeluserstat',
            name='users_ep',
            field=models.IntegerField(help_text='# of channel users when proxy promotion ends', null=True, verbose_name='ending promotion'),
        ),
        migrations.AddField(
            model_name='channeluserstat',
            name='users_sp',
            field=models.IntegerField(help_text='# of channel users before proxy promotion', null=True, verbose_name='before promotion'),
        ),
        migrations.AddField(
            model_name='mtproxy',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channeluserstat',
            name='channel',
            field=models.CharField(db_index=True, max_length=150, verbose_name='promoted_channel'),
        ),
        migrations.AlterIndexTogether(
            name='channeluserstat',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='channeluserstat',
            name='proxy',
        ),
        migrations.RemoveField(
            model_name='channeluserstat',
            name='statistics',
        ),
        migrations.RunPython(update_slugs)
    ]
