# Generated by Django 2.2.2 on 2019-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0007_auto_20191010_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtproxy',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='mtproxy',
            unique_together=set(),
        ),
    ]
