# Generated by Django 2.2.2 on 2019-10-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0008_auto_20191010_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelStatProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('channel_stat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promoter.ChannelUserStat')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promoter.MTProxy')),
            ],
            options={
                'db_table': 'mtproxy_channel_stats_proxies',
            },
        ),
    ]
