# Generated by Django 2.2.2 on 2019-06-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ping_checker_domain_list',
            },
        ),
        migrations.CreateModel(
            name='DomainPingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('latency', models.FloatField(null=True)),
                ('success_percentage', models.IntegerField()),
                ('is_ping', models.BooleanField(verbose_name='was pinged?')),
                ('ping_code', models.TextField(verbose_name='ping result')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ping_checker.DomainName')),
            ],
            options={
                'db_table': 'ping_checker_domain_log',
            },
        ),
    ]