# Generated by Django 2.2.2 on 2019-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=60, verbose_name='bot name')),
                ('token', models.CharField(max_length=45, unique=True, verbose_name='token')),
            ],
            options={
                'db_table': 'telegram_bots',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=60, verbose_name='channel title')),
                ('channel_id', models.BigIntegerField(unique=True, verbose_name='channel id')),
                ('username', models.CharField(max_length=60, verbose_name='username')),
            ],
            options={
                'db_table': 'telegram_channels',
            },
        ),
    ]
