# Generated by Django 2.2.2 on 2019-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='username')),
                ('number', models.CharField(max_length=13, unique=True, verbose_name='phone number')),
                ('api_id', models.PositiveIntegerField(unique=True, verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=32, verbose_name='API Hash')),
                ('is_enable', models.BooleanField(default=False, editable=False, verbose_name='is login')),
            ],
            options={
                'db_table': 'telegram_users',
            },
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='bot name'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='channel_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='channel id'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='channel title'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='username'),
        ),
    ]
