# Generated by Django 2.2.2 on 2019-10-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tel_tools', '0002_auto_20190828_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(blank=True, help_text='fill if you enabled two-step verification', max_length=100, verbose_name='two-step verification code'),
        ),
    ]
