# Generated by Django 2.2.2 on 2019-06-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('zone_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dns_domains',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'dns_servers',
            },
        ),
        migrations.CreateModel(
            name='ServerIPBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('used_time', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server')),
            ],
            options={
                'db_table': 'dns_servers_ip',
            },
        ),
        migrations.CreateModel(
            name='DomainNameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sub_domain_name', models.CharField(max_length=20, unique=True)),
                ('ip', models.CharField(max_length=15)),
                ('dns_record', models.CharField(blank=True, editable=False, max_length=32)),
                ('is_enable', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.DomainZone')),
            ],
            options={
                'db_table': 'dns_domains_records',
            },
        ),
        migrations.CreateModel(
            name='DomainLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(db_index=True, max_length=15)),
                ('api_response', models.TextField()),
                ('domain_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.DomainNameRecord')),
            ],
            options={
                'db_table': 'dns_domains_records_logs',
            },
        ),
    ]
