# Generated by Django 2.2.2 on 2019-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainlogger',
            options={'verbose_name': 'Domain Record Log'},
        ),
        migrations.AlterModelOptions(
            name='domainnamerecord',
            options={'verbose_name': 'Domain Record'},
        ),
        migrations.AlterModelOptions(
            name='domainzone',
            options={'verbose_name': 'Domain'},
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='sub_domain_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='domainzone',
            name='domain_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='used_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='domainnamerecord',
            unique_together={('sub_domain_name', 'domain')},
        ),
    ]
