# Generated by Django 2.2.2 on 2019-07-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0002_auto_20190626_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_name', models.CharField(max_length=50)),
                ('net_detect_pattern', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dns_isp',
            },
        ),
        migrations.RenameModel(
            old_name='DomainLogger',
            new_name='DNSUpdateLog',
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server'),
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='ip',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterModelTable(
            name='dnsupdatelog',
            table='dns_update_logs',
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='network',
            field=models.ManyToManyField(to='dns_updater.InternetServiceProvider'),
        ),
    ]
