# Generated by Django 2.2.2 on 2019-07-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0003_auto_20190704_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetserviceprovider',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='network',
            field=models.ManyToManyField(blank=True, to='dns_updater.InternetServiceProvider'),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_updater.Server'),
        ),
    ]
