# Generated by Django 2.2.2 on 2019-08-14 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0004_auto_20190709_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsupdatelog',
            options={'verbose_name': 'DNS Update Log'},
        ),
        migrations.AlterModelOptions(
            name='internetserviceprovider',
            options={'verbose_name': 'ISP'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server'},
        ),
        migrations.AlterModelOptions(
            name='serveripbank',
            options={'verbose_name': 'Server IP Bank'},
        ),
        migrations.RemoveField(
            model_name='domainnamerecord',
            name='network',
        ),
        migrations.AddField(
            model_name='domainnamerecord',
            name='proxy_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainzone',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_path_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='filter_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='last_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dnsupdatelog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='server ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, verbose_name='server name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server'),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
    ]
