# Generated by Django 2.2.2 on 2019-07-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0004_auto_20190709_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsupdatelog',
            options={'verbose_name': 'DNS Update Log'},
        ),
        migrations.AlterModelOptions(
            name='internetserviceprovider',
            options={'verbose_name': 'ISP'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server'},
        ),
        migrations.AlterModelOptions(
            name='serveripbank',
            options={'verbose_name': 'Server IP Bank'},
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='domainnamerecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server'),
        ),
    ]
