# Generated by Django 2.2.2 on 2019-08-11 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0004_auto_20190709_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsupdatelog',
            options={'verbose_name': 'DNS Update Log'},
        ),
        migrations.AlterModelOptions(
            name='internetserviceprovider',
            options={'verbose_name': 'ISP'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server'},
        ),
        migrations.AlterModelOptions(
            name='serveripbank',
            options={'verbose_name': 'Server IP Bank'},
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_path_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='filter_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='last_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='server ip'),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server'),
        ),
    ]
