# Generated by Django 2.2.2 on 2019-08-07 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0005_auto_20190731_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_path_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='server ip'),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dns_updater.Server'),
        ),
    ]
