# Generated by Django 2.2.2 on 2019-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0005_auto_20190814_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveripbank',
            name='is_set',
        ),
        migrations.RemoveField(
            model_name='serveripbank',
            name='last_check',
        ),
        migrations.AddField(
            model_name='serveripbank',
            name='last_check_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='filter_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serveripbank',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
