# Generated by Django 2.2.2 on 2019-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0006_auto_20190828_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveripbank',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
