# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-09 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainlist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
