# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_checker', '0002_auto_20190609_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('latency', models.IntegerField()),
                ('success_percentage', models.IntegerField()),
                ('ping', models.BooleanField()),
            ],
            options={
                'db_table': 'ping_checker_domain_log',
            },
        ),
        migrations.RenameModel(
            old_name='DomainList',
            new_name='DomainName',
        ),
        migrations.RenameField(
            model_name='domainname',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='domainname',
            old_name='updated_date',
            new_name='updated_time',
        ),
        migrations.AddField(
            model_name='domainpinglog',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_checker.DomainName'),
        ),
    ]
