# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-09 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_checker', '0003_auto_20190609_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainpinglog',
            old_name='ping',
            new_name='is_ping',
        ),
    ]
