# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_checker', '0004_auto_20190609_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainpinglog',
            name='latency',
            field=models.IntegerField(null=True),
        ),
    ]
