# Generated by Django 2.2.2 on 2019-07-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_updater', '0004_auto_20190709_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('network_name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=15)),
                ('is_ping', models.BooleanField(verbose_name='was pinged?')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dns_updater.InternetServiceProvider')),
            ],
            options={
                'db_table': 'dns_ping_log',
            },
        ),
    ]
