# Generated by Django 2.2.2 on 2019-07-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pinglog',
            table='ping_log',
        ),
    ]
